In [2]:
import numpy as np

In [2]:
v1= np.array([1, 2, 3])
v2= np.array([3,2,1])

In [3]:
v1+v2

array([4, 4, 4])

In [4]:
v1-v2

array([-2,  0,  2])

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[3]

np.int64(4)

In [8]:
#Like List Array is also Mutable
a[3] = 10

In [9]:
a[3]


np.int64(10)

In [4]:
#Slice also Works on Array
a[:3]

array([1, 2, 3])

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.ndim

2

In [8]:
a.shape

(3, 4)

In [9]:
len(a.shape) == a.ndim

True

In [10]:
import math
a.size == math.prod(a.shape)

True

In [11]:
a.dtype

dtype('int64')

In [12]:
pip install Faker

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
from faker import Faker
fake = Faker()

In [15]:
fake.name()

'Misty Wheeler'

In [16]:
from faker import Faker
from faker.providers import internet

fake = Faker()
fake.add_provider(internet)

print(fake.ipv4_private())

172.29.176.234


In [1]:
from faker import Faker
fake = Faker()

In [3]:
print(fake.name()*10)

Shannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon MorrisShannon Morris


In [4]:
for i in range(10):
    print(fake.name())

Jennifer Poole
John Woodard
Mr. Michael Holt
Margaret Preston
Charles Mcneil
Christopher Davis
Mary Melendez
Anita Burns
Patricia Hobbs
Robert Guerra


In [7]:
for i in range(10):
    print(fake.name())
    print(fake.ipv4_private())
    print(fake.address())
    print("------------")

Erica Wright
10.77.213.7
3589 Lawrence Mountain Suite 300
Lake James, MO 53912
------------
Kenneth Miller
10.12.138.32
156 Frederick Causeway
Griffinfurt, AK 98424
------------
Jessica Gardner
172.24.103.167
30613 Willie Route Apt. 488
North Christophershire, AR 06642
------------
Maria Bradley
192.168.56.7
21242 Spencer Green Suite 299
Port Tiffanyfurt, NC 09590
------------
Tiffany Williams
10.107.64.176
22189 Scott Isle Apt. 887
Coxburgh, AS 09487
------------
Jessica Swanson
172.26.123.233
60783 Elliott Village
Thomastown, WY 02420
------------
Christina Roberson
172.24.129.58
5052 Christian Harbors
East Erikaport, ME 93382
------------
Brett Adkins MD
192.168.185.85
686 Reynolds Motorway
Martinezfurt, CO 18933
------------
Derek Espinoza
10.168.16.72
430 John Cape
Smithbury, MD 84425
------------
Kevin Smith
192.168.189.186
8318 Campbell Gateway
New Danielfurt, MN 60840
------------
